#include <Arduino.h>
#include <M5Core2.h>
#include "ui/lv_setup.h"
#include "ui/ui.h"
#include "time_func.h"

void setup()
{
  M5.begin();  // Initialize the M5Stack peripherals
  lv_begin();  // Initialize LVGL for the Core2 screen
  ui_init();   // Initialize UI generated by Square Line
  time_init(); // Initialize time and date from compiler
}

void loop()
{
  lv_handler();  // Update UI
  update_time(); // Update time and date on UI
}