#include <Arduino.h>
#ifdef M5UNIFIED
#include <M5Unified.h>
#else
#include <M5Core2.h>
#endif

#include "time_func.h"
#include "ui/lv_setup.h"
#include "ui/ui.h"

void setup() {
#ifdef ARDUINO_M5STACK_CORES3
  delay(3000); //let USB settle so as we do not lose startup messages
#endif
  M5.begin();  // Initialize the M5Stack peripherals
  lv_begin();  // Initialize LVGL for the Core2 screen
  ui_init();   // Initialize UI generated by Square Line
  time_init(); // Initialize time and date from compiler
}

void loop() {
  lv_handler();  // Update UI
  update_time(); // Update time and date on UI
}